name: .NET Core

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "*"

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Test
        run: |
          dotnet test

      - name: Bundle
        run: |
          dotnet restore -r osx-x64
          dotnet msbuild -t:BundleApp -p:RuntimeIdentifier=osx-x64 -property:Configuration=Release -p:UseAppHost=true

      - name: Sign
        run: |
          ~/buildscripts/signapp.sh

      - name: Notarize Release Build
        uses: devbotsxyz/xcode-notarize@v1
        with:
          product-path: "~/publish/Rings.app"
          appstore-connect-username: ${{ secrets.NOTARIZATION_USERNAME }}
          appstore-connect-password: ${{ secrets.NOTARIZATION_PASSWORD }}

      - name: Staple Release Build
        uses: devbotsxyz/xcode-staple@v1
        with:
          product-path: "~/publish/Rings.app"

      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: StationHub-osx-x64
          path: ~/publish